import assert from "node:assert/strict";
import { judgeOpportunity } from "./judge.js";
import { demandFingerprint } from "./sources.js";

function judged(x) {
  return judgeOpportunity({
    source_item_id: "test",
    type: "unknown",
    title: "",
    description: "",
    skills: "",
    budget_min: null,
    budget_max: null,
    currency: "",
    location: "Online",
    posted_at: new Date().toISOString(),
    ...x
  });
}

assert.equal(
  demandFingerprint("Feature request: add CSV export for weekly reports"),
  "csv_export"
);
assert.equal(
  demandFingerprint("Please add Markdown export for documentation"),
  "markdown_export"
);
assert.equal(
  demandFingerprint("TikTok and YouTube media downloader with custom quality"),
  "multi_platform_downloader"
);
assert.notEqual(
  demandFingerprint("Feature request: add CSV export"),
  demandFingerprint("Feature request: add PDF export")
);

const falsePaid = judged({
  source: "github_paid",
  type: "bounty_unverified",
  title: "Which client jobs can my system deliver?",
  description: "I want paid work from Fiverr and Upwork. Research which jobs I could do."
});
assert.equal(falsePaid.grade, "cold");
assert.equal(falsePaid.breakdown.payout_kind, "no_reward_evidence");

const micro = judged({
  source: "github_paid",
  type: "bounty_unverified",
  title: "Expose inference metrics",
  description: "Bounty: $1 USDC. Apply on the dashboard and link a Solana wallet.",
  budget_min: 1,
  budget_max: 1,
  currency: "USDC"
});
assert.equal(micro.grade, "cold");
assert.equal(micro.breakdown.usd_estimate, 1);

const token = judged({
  source: "github_paid",
  type: "bounty_unverified",
  title: "Build bounties (25-150 RTC)",
  description: "Claim work and get paid in RTC.",
  budget_min: 25,
  budget_max: 150,
  currency: "RTC",
  skills: "automation, api"
});
assert.equal(token.breakdown.payout_kind, "token_fixed");
assert.equal(token.breakdown.requires_pay_check, true);

const legacyDemand = judged({
  source: "github_demand",
  type: "business_opportunity",
  title: "Add CSV export",
  description: "Feature request: there is no CSV export and users need reports.",
  skills: "demand_group:reporting_export, demand_repeat:3, demand_problem:yes, csv, automation"
});
assert.equal(legacyDemand.grade, "cold");
assert.equal(legacyDemand.breakdown.demand_status, "legacy_signal");

const singleDemand = judged({
  source: "github_demand",
  type: "business_opportunity",
  title: "Add CSV export",
  description: "Feature request: there is no CSV export and users need reports.",
  skills: "demand_group:reporting_export, demand_fingerprint:csv_export, demand_repeat:1, demand_problem:yes, csv, automation"
});
assert.equal(singleDemand.grade, "cold");
assert.equal(singleDemand.breakdown.demand_status, "signal");
assert.equal(singleDemand.breakdown.demand_fingerprint, "csv_export");

const repeatedDemand = judged({
  source: "github_demand",
  type: "business_opportunity",
  title: "Add CSV export",
  description: "Feature request: there is no CSV export and users need reports.",
  skills: "demand_group:reporting_export, demand_fingerprint:csv_export, demand_repeat:3, demand_problem:yes, csv, automation"
});
assert.equal(repeatedDemand.grade, "watch");
assert.equal(repeatedDemand.breakdown.demand_status, "product_candidate");

const broadGroupButDifferentProblem = judged({
  source: "github_demand",
  type: "business_opportunity",
  title: "Add PDF export",
  description: "Feature request: there is no PDF export for reports.",
  skills: "demand_group:reporting_export, demand_fingerprint:pdf_export, demand_repeat:1, demand_problem:yes, pdf"
});
assert.equal(broadGroupButDifferentProblem.grade, "cold");

const noise = judged({
  source: "github_demand",
  type: "business_opportunity",
  title: "GitHub Trending Daily",
  description: "Generated by GitHub Actions. Daily digest generated at: now.",
  skills: "demand_group:other, demand_fingerprint:lex_trending_daily_github, demand_repeat:4, demand_problem:yes, automation"
});
assert.equal(noise.grade, "cold");
assert.equal(noise.breakdown.demand_status, "noise");

console.log("validator tests: OK");
