const SQL=[
"CREATE TABLE IF NOT EXISTS intake_jobs (intake_job_id TEXT PRIMARY KEY,opportunity_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'received',file_count INTEGER NOT NULL DEFAULT 0,ready_count INTEGER NOT NULL DEFAULT 0,review_count INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
"CREATE TABLE IF NOT EXISTS intake_files (intake_file_id TEXT PRIMARY KEY,intake_job_id TEXT NOT NULL,file_name TEXT NOT NULL,mime_type TEXT NOT NULL DEFAULT '',file_kind TEXT NOT NULL DEFAULT 'unknown',document_type TEXT NOT NULL DEFAULT 'unknown',extraction_status TEXT NOT NULL DEFAULT 'pending',confidence REAL NOT NULL DEFAULT 0,metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
"CREATE INDEX IF NOT EXISTS idx_intake_files_job ON intake_files(intake_job_id,created_at)",
"CREATE TABLE IF NOT EXISTS intake_review_queue (review_id TEXT PRIMARY KEY,intake_job_id TEXT NOT NULL,intake_file_id TEXT NOT NULL,reason_code TEXT NOT NULL,candidates_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'pending',resolution_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
"CREATE INDEX IF NOT EXISTS idx_intake_review_status ON intake_review_queue(status,created_at)",
"CREATE TABLE IF NOT EXISTS extraction_jobs (extraction_job_id TEXT PRIMARY KEY,intake_job_id TEXT NOT NULL DEFAULT '',intake_file_id TEXT NOT NULL DEFAULT '',provider TEXT NOT NULL DEFAULT 'pc_ocr',mode TEXT NOT NULL DEFAULT 'ocr',status TEXT NOT NULL DEFAULT 'queued',source_ref TEXT NOT NULL DEFAULT '',result_json TEXT NOT NULL DEFAULT '{}',error_text TEXT NOT NULL DEFAULT '',claimed_at TEXT,completed_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)",
"CREATE INDEX IF NOT EXISTS idx_extraction_jobs_queue ON extraction_jobs(provider,status,created_at)",
"CREATE TABLE IF NOT EXISTS pc_workers (worker_id TEXT PRIMARY KEY,last_seen_at TEXT NOT NULL,capabilities_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'offline',endpoint_url TEXT NOT NULL DEFAULT '')",
"CREATE TABLE IF NOT EXISTS pc_upload_tickets (ticket_id TEXT PRIMARY KEY,worker_id TEXT NOT NULL DEFAULT 'home-pc',file_name TEXT NOT NULL DEFAULT '',expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL)"
];let ready=false;
export async function ensureFactorySchema(db){if(ready||!db)return;for(const sql of SQL)await db.prepare(sql).run();const cols=await db.prepare("PRAGMA table_info(pc_workers)").all();if(!(cols.results||[]).some(x=>x.name==="endpoint_url"))await db.prepare("ALTER TABLE pc_workers ADD COLUMN endpoint_url TEXT NOT NULL DEFAULT ''").run();ready=true}
