export function factoryHtml(){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Exception Factory</title><style>
*{box-sizing:border-box}body{margin:0;font-family:system-ui,sans-serif;background:#f6f7f9;color:#15171a}.wrap{max-width:760px;margin:auto;padding:18px}.hero{padding:20px 4px 14px}.hero h1{margin:0 0 7px;font-size:27px}.hero p{margin:0;color:#666;line-height:1.45}.card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:16px;margin:12px 0;box-shadow:0 2px 10px #00000008}.drop{border:2px dashed #c9ced6;border-radius:14px;padding:25px 14px;text-align:center}.drop input{width:100%;margin-top:12px}.muted{color:#70757d;font-size:13px}.file{padding:11px 0;border-bottom:1px solid #eee}.file:last-child{border:0}.pill{display:inline-block;border-radius:99px;padding:4px 8px;font-size:12px;background:#eef1f5;margin-left:6px}.ok{background:#e8f7ee}.warn{background:#fff4d6}.btn{width:100%;border:0;border-radius:12px;padding:14px;font-weight:700;font-size:16px;background:#15171a;color:#fff}.btn:disabled{opacity:.35}.kpis{display:grid;grid-template-columns:1fr 1fr;gap:9px}.kpi{background:#f7f8fa;border-radius:12px;padding:12px}.n{font-size:23px;font-weight:800}.finding{border-left:4px solid #d0d4da;padding:8px 11px;margin:10px 0;background:#fafafa}.error{color:#a40000}</style></head><body><main class="wrap"><section class="hero"><h1>Exception Factory</h1><p>평소 쓰던 자료를 그대로 올리세요. 주문·송장·가격 자료를 비교해 잠재적인 금액 불일치를 찾습니다.</p></section><section class="card"><div class="drop"><strong>파일 여러 개 선택</strong><div class="muted">CSV · TSV · JSON · TXT는 지금 바로 분석 가능<br>XLSX · PDF · 이미지 · ZIP은 추출 계층 연결 예정</div><input id="files" type="file" multiple accept=".csv,.tsv,.json,.txt,.xlsx,.xls,.pdf,.png,.jpg,.jpeg,.webp,.zip"></div><div id="list"></div></section><section class="card"><label>자료 역할</label><p class="muted">현재 직접 분석 파일은 이름으로 주문/송장/가격표를 자동 추정합니다. 잘못 추정되면 아래에서 변경할 수 있습니다.</p><div id="roles"></div><button id="run" class="btn" disabled>무료 Leak Scan 실행</button><div id="err" class="error"></div></section><section id="result" class="card" hidden></section></main><script>
const filesEl=document.getElementById('files'),list=document.getElementById('list'),roles=document.getElementById('roles'),run=document.getElementById('run'),result=document.getElementById('result'),err=document.getElementById('err');let items=[];
const ext=n=>(n.split('.').pop()||'').toLowerCase(),direct=e=>['csv','tsv','json','txt'].includes(e),guess=n=>/invoice|송장|청구/i.test(n)?'invoices':/price|cost|가격|단가/i.test(n)?'priceList':'orders';
function parseDelimited(t,d){const lines=t.trim().split(/\r?\n/);if(!lines.length)return[];const h=lines[0].split(d).map(x=>x.trim());return lines.slice(1).filter(Boolean).map(line=>{const v=line.split(d);return Object.fromEntries(h.map((x,i)=>[x,v[i]?.trim()??'']))})}
function parseText(t,e){if(e==='json'){const j=JSON.parse(t);return Array.isArray(j)?j:(j.rows||[])}return parseDelimited(t,e==='tsv'?'\t':',')}
function render(){list.innerHTML=items.map((x,i)=>'<div class="file"><b>'+x.file.name+'</b><span class="pill '+(x.direct?'ok':'warn')+'">'+(x.direct?'브라우저 분석 가능':'추출 엔진 필요')+'</span><div class="muted">'+Math.ceil(x.file.size/1024)+' KB</div></div>').join('');roles.innerHTML=items.filter(x=>x.direct).map((x,i)=>'<div class="file">'+x.file.name+' <select data-name="'+x.file.name+'"><option value="orders" '+(x.role==='orders'?'selected':'')+'>주문자료</option><option value="invoices" '+(x.role==='invoices'?'selected':'')+'>송장/청구</option><option value="priceList" '+(x.role==='priceList'?'selected':'')+'>가격표</option></select></div>').join('');run.disabled=!items.some(x=>x.direct)}
filesEl.onchange=()=>{items=[...filesEl.files].map(file=>({file,direct:direct(ext(file.name)),role:guess(file.name)}));render()};
run.onclick=async()=>{err.textContent='';run.disabled=true;run.textContent='분석 중…';try{const body={orders:[],invoices:[],priceList:[],scanMode:'free'};for(const x of items.filter(x=>x.direct)){const sel=roles.querySelector('select[data-name="'+CSS.escape(x.file.name)+'"]');x.role=sel?.value||x.role;const rows=parseText(await x.file.text(),ext(x.file.name));body[x.role].push(...rows)}if(!body.invoices.length)throw new Error('송장/청구 자료가 최소 1개 필요합니다.');const r=await fetch('/api/factory/audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'분석 실패');const h=j.free_summary.headline;result.hidden=false;result.innerHTML='<h2>Free Leak Scan</h2><div class="kpis"><div class="kpi"><div class="n">'+h.transactions_checked+'</div><div>검증 건수</div></div><div class="kpi"><div class="n">'+h.potential_discrepancies+'</div><div>잠재 이상</div></div><div class="kpi"><div class="n">'+h.potential_money_exposure.amount+'</div><div>잠재 금액 노출</div></div><div class="kpi"><div class="n">'+h.human_review_required+'</div><div>사람 확인 필요</div></div></div>'+j.free_summary.sample_findings.map(f=>'<div class="finding"><b>'+f.label+'</b><br><span class="muted">Order '+f.order_id+' · SKU '+f.sku+' · review recommended</span></div>').join('')+(j.free_summary.hidden_finding_count?'<p><b>추가 '+j.free_summary.hidden_finding_count+'건</b>의 상세 결과가 있습니다.</p>':'')+'<p class="muted">'+j.free_summary.disclaimer+'</p>'}catch(e){err.textContent=e.message}finally{run.disabled=false;run.textContent='무료 Leak Scan 실행'}};
</script></body></html>`}
